//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuvVision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public Nullable<int> U_Role_ID { get; set; }
        public string Created_By { get; set; }
        public Nullable<int> Status { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Qualification { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<System.DateTime> DateOf_Joining { get; set; }
        public Nullable<System.DateTime> RelievingDate { get; set; }
        public string Password { get; set; }
        public string Branch { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string ZipCode { get; set; }
        public string Signature { get; set; }
        public string EmployeeCode { get; set; }
        public string Designation { get; set; }
        public string EmployeeGrade { get; set; }
        public string OfficeNo { get; set; }
        public string ResiNo { get; set; }
        public string MobileNo { get; set; }
        public string SAP_Vandor_code { get; set; }
        public string Active { get; set; }
        public string Language_Spoken { get; set; }
        public string Employment_Type { get; set; }
        public string Reporting_To { get; set; }
        public string DeleteStatus { get; set; }
        public string Service_Type { get; set; }
        public string Cost_center { get; set; }
        public string Image { get; set; }
        public string CV { get; set; }
        public string Reporting2 { get; set; }
        public string Vendor_Code { get; set; }
        public string Fax_No { get; set; }
        public string Gender { get; set; }
        public string Marital_Status { get; set; }
        public string BloodGroup { get; set; }
        public string ShoesSize { get; set; }
        public string ShirtSize { get; set; }
        public string PanNo { get; set; }
        public string AadharNo { get; set; }
        public string TotalyearofExprience { get; set; }
        public string Allergies { get; set; }
        public string Medical_History { get; set; }
        public string Additional_Qualification { get; set; }
        public string EmergencyMobile_No { get; set; }
        public string Salutation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
