//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuvVision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchMaster
    {
        public int Br_Id { get; set; }
        public string Branch_Name { get; set; }
        public string Branch_Code { get; set; }
        public string Manager { get; set; }
        public string Service_Code { get; set; }
        public string Sequence_Number { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Postal_Code { get; set; }
        public string Email_Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
        public string DeleteStatus { get; set; }
        public string CreatedBy { get; set; }
        public string CityName { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string BranchAdmin { get; set; }
        public string Attachment { get; set; }
        public string Coordinator_Email_Id { get; set; }
    }
}
