//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuvVision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostSheetMaster
    {
        public int PK_Cs_Id { get; set; }
        public string Costsheet { get; set; }
        public Nullable<int> EQ_ID { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string Status { get; set; }
        public Nullable<int> Orderby { get; set; }
    }
}
