//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuvVision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public int Id { get; set; }
        public string inventoryCode { get; set; }
        public string inventoryName { get; set; }
        public Nullable<decimal> inventoryPrice { get; set; }
        public string inventoryAvailability { get; set; }
        public string inventoryTamilName { get; set; }
        public string inventoryImageURL { get; set; }
    }
}
