//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuvVision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryMaster
    {
        public int Lib_Id { get; set; }
        public string FolderName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> PK_SubSubID { get; set; }
        public string Status { get; set; }
    }
}
