//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuvVision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleM_LeftSubCategory
    {
        public int LeftSubCat_Id { get; set; }
        public Nullable<int> LeftMenucat_Id { get; set; }
        public string SubCat_Name { get; set; }
        public string R_Controller { get; set; }
        public string R_Action { get; set; }
        public string Optional_ID { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string Status { get; set; }
    }
}
