//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuvVision.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestKioskApiEntities : DbContext
    {
        public TestKioskApiEntities()
            : base("name=TestKioskApiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ItemMaster> ItemMasters { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<RoleM_LeftSubCategory> RoleM_LeftSubCategory { get; set; }
        public virtual DbSet<RoleM_MenuCategory> RoleM_MenuCategory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<RoleM_SubSubCategory> RoleM_SubSubCategory { get; set; }
        public virtual DbSet<BranchMaster> BranchMasters { get; set; }
        public virtual DbSet<LibraryDocument> LibraryDocuments { get; set; }
        public virtual DbSet<LibraryMaster> LibraryMasters { get; set; }
        public virtual DbSet<InvoicingInstruction> InvoicingInstructions { get; set; }
    }
}
